config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get '/signup', to: 'users#new'
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください。"
      redirect_to login_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @post
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to @post
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "投稿しました。"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "削除しました。"
    redirect_to root_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "ログインしました。"
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスとパスワードの組み合わせが正しくありません。'
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @post = current_user.posts.build if logged_in?
    @posts = Post.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザー登録しました。"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "アカウントを変更しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "アカウントを削除しました。"
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= link_to "BBS", root_path, id: "logo" %>
        <nav>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <% if logged_in? %>
              <li><%= link_to "アカウント", current_user %></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "ログイン", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :title, placeholder: "タイトル" %>
    <%= f.text_area :content, placeholder: "詳細" %>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user_info.html.erb
<h1><%= current_user.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | BBS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="title"><%= link_to post.title, post %></span>
  <span class="timestamp">
    <%= post.created_at %>
  </span>
</li>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <ul class="posts">
      <li>
        <span class="title"><%= @post.title %></span>
        <span class="user"><%= @post.user.name %></span>
        <span class="timestamp"><%= @post.created_at %></span>
        <span class="content"><%= @post.content %></span>
      </li>
    </ul>

    <% if current_user == @post.user %>
      <%= link_to "削除", @post, method: :delete,
                                           data: { confirm: "削除しますか?" }, class: "btn btn-danger" %>
    <% end %>

    <h3>レス一覧</h3>
    <% @comments.each do |c| %>
      <div class="comments">
        <li>
          <span class="user"><%= c.user.name %></span>
          <span class="timestamp">
            <%= c.created_at %>
          </span>
          <span class="content">
            <%= c.content %>
          </span>
        </li>
      </div>
    <% end %>

    <%= form_for [@post, @comment] do |f| %>
      <%= f.text_field :content %>
      <br>
      <%= f.submit 'コメントする', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% if logged_in? %>
      <section class="post_form">
        <%= render 'layouts/post_form' %>
      </section>
      <h3>スレッドタイトル</h3>
      <ul class="posts">
        <% @posts.each do |post| %>
          <li>
            <%= link_to post.title, post %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <h1>BBSへようこそ</h1>
      <%= link_to "新規登録", signup_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<h1>アカウント変更</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', object: f.object %>

      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :メールアドレス %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "保存", class: "btn btn-primary" %>
    <% end %>
    <%= link_to "アカウント削除", @user, method: :delete,
                                  data: { confirm: "アカウントを削除してもよろしいですか？" }, class: "btn btn-danger" %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', object: f.object %>

      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :メールアドレス %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "アカウント作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>
      <%= @user.name %>
    </h1>
    <% if @user == current_user %>
    <%= link_to "アカウント変更", edit_user_path(current_user), class: "btn btn-primary" %>
    <% end %>

    <div>
      <h3>スレッドタイトル</h3>
      <% if @user.posts.any? %>
        <ol class="posts">
          <%= render @posts %>
        </ol>
        <%= paginate @posts %>
      <% end %>
    </div>
  </div>
</div>